id: P006658
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:13:45.886759
source_metadata:
  id: bdr:W1AC270
  title: ཕྱིར་རྟོག་དང་འཚོལ་སྙེག
  author: ''
  volumes:
    06da3b1a32564bbe9734e42ab9a99060:
      image_group_id: I2PD20343
      title: ''
      volume_number: 1
      total_pages: 326
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
